version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      
  pre_build:
    commands:
      - echo Pre-build phase complete.

  build:
    commands:
      - echo Build started on `date`
      - python app.py  # รันคำสั่งสำหรับรันแอปพลิเคชัน

  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - '**/*'
