version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt  # ติดตั้ง dependencies
  build:
    commands:
      - echo Build started on `date`
      - python app.py  # หรือคำสั่งสำหรับรันโปรเจกต์ของคุณ
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'  # ไฟล์ที่ต้องการจัดเก็บหลังการ build
