version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x # เปลี่ยนเป็นเวอร์ชันที่คุณต้องการ
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running pre-build commands"
  build:
    commands:
      - echo "Building the application"
      - eb deploy # ใช้คำสั่ง deploy ไปยัง Elastic Beanstalk

artifacts:
  files:
    - '**/*'
